- name: Проверка соединения с нодой
  hosts: NexCloud
  tasks:
    - name: Пинг для проверки подключения
      ping:

    - name: Задержка перед обновлением apt
      pause:
        seconds: 30

    - name: Принудительное обновление кэша apt
      apt:
        update_cache: yes
      become: true

    - name: Установить пакет `btop`
      apt:
        name: btop
        state: present
      become: true
