- name: Check connection to nodes
  hosts: NexCloud
  tasks:
    - name: Ping to check connectivity
      ping:
    - name: Установить пакет `btop`
      apt:
        name: btop
        state: present
        update_cache: yes
      become: true
